#!/bin/bash
# Regenerate THIRD-PARTY-LICENSES.md from the resolved Swift Package Manager
# checkouts, reproducing each dependency's license text verbatim.
#
#   scripts/collect_licenses.sh [--source-packages DIR] [--check]
#
#   --source-packages  SPM working directory (default: <repo>/build/SourcePackages).
#                      Produced by any xcodebuild run with -derivedDataPath build.
#   --check            Do not write; exit non-zero if THIRD-PARTY-LICENSES.md is
#                      out of date. For wiring into CI later.
#
# Both Sparkle and ZIPFoundation are MIT-family licenses that require their
# copyright notice to ship "in all copies or substantial portions" — that
# obligation attaches to the DMG we distribute, not just to the source. The
# generated file is committed AND bundled into the app's Resources
# (see project.yml) so the notices travel with the binary.
#
# This script fails when a dependency has no discoverable license file rather
# than skipping it, so adding a package cannot silently ship unattributed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_PACKAGES="$REPO_ROOT/build/SourcePackages"
OUTPUT="$REPO_ROOT/THIRD-PARTY-LICENSES.md"
CHECK_ONLY=0

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --source-packages) SOURCE_PACKAGES="${2:?--source-packages needs a value}"; shift 2 ;;
        --check) CHECK_ONLY=1; shift ;;
        -h|--help) sed -n '2,/^set -euo/p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'; exit 0 ;;
        *) die "unknown argument: $1 (try --help)" ;;
    esac
done

STATE="$SOURCE_PACKAGES/workspace-state.json"
[[ -f "$STATE" ]] \
    || die "no SPM state at $STATE — build once first (xcodebuild ... -derivedDataPath build build)"

# How each dependency reaches the user. Keyed by SPM identity; anything
# resolved but not described here is reported so it cannot be forgotten.
describe() {
    case "$1" in
        sparkle) echo "Embedded as \`Contents/Frameworks/Sparkle.framework\`." ;;
        zipfoundation) echo "Statically linked into the app and both Quick Look extensions." ;;
        *) echo "Bundled with the application." ;;
    esac
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<'HEADER'
# Third-party licenses

3MF QuickLook is distributed under the MIT license (see `LICENSE`). The
released application also contains the third-party components below. Their
license texts are reproduced verbatim, as those licenses require.

This file is generated by `scripts/collect_licenses.sh` from the resolved
Swift Package Manager checkouts — do not edit it by hand. It ships inside the
application bundle (`Contents/Resources/THIRD-PARTY-LICENSES.md`) so the
notices travel with the binary, not just with the source.
HEADER

# identity<TAB>version<TAB>location, in a stable order.
while IFS=$'\t' read -r identity version location; do
    [[ -n "$identity" ]] || continue

    checkout="$SOURCE_PACKAGES/checkouts/$identity"
    if [[ ! -d "$checkout" ]]; then
        # SPM directory names follow the repo name, which need not match the
        # lowercased identity.
        checkout="$(find "$SOURCE_PACKAGES/checkouts" -maxdepth 1 -type d -iname "$identity" | head -n 1)"
    fi
    [[ -n "$checkout" && -d "$checkout" ]] || die "no checkout found for dependency '$identity'"

    license="$(find "$checkout" -maxdepth 1 \( -iname 'LICENSE' -o -iname 'LICENSE.*' -o -iname 'COPYING' -o -iname 'COPYING.*' \) | head -n 1)"
    [[ -n "$license" ]] \
        || die "dependency '$identity' has no license file in $checkout — it cannot be distributed unattributed"

    # Title-case the identity for display, preserving known casing.
    case "$identity" in
        sparkle) display="Sparkle" ;;
        zipfoundation) display="ZIPFoundation" ;;
        *) display="$identity" ;;
    esac

    {
        printf '\n---\n\n## %s\n\n' "$display"
        printf '%s\n' "$(describe "$identity")"
        printf 'Version %s — %s\n\n' "${version:-unknown}" "${location%.git}"
        printf '```\n'
        cat "$license"
        printf '```\n'
    } >> "$TMP"
done < <(python3 - "$STATE" <<'PY'
import json, sys
state = json.load(open(sys.argv[1]))
for dep in sorted(state["object"]["dependencies"], key=lambda d: d["packageRef"]["identity"]):
    ref = dep["packageRef"]
    version = dep.get("state", {}).get("checkoutState", {}).get("version", "")
    print("\t".join([ref["identity"], version, ref.get("location", "")]))
PY
)

if [[ "$CHECK_ONLY" -eq 1 ]]; then
    if cmp -s "$TMP" "$OUTPUT"; then
        echo "THIRD-PARTY-LICENSES.md is up to date"
        exit 0
    fi
    die "THIRD-PARTY-LICENSES.md is out of date — run scripts/collect_licenses.sh"
fi

cp "$TMP" "$OUTPUT"
echo "wrote $OUTPUT"
grep '^## ' "$OUTPUT" | sed 's/^## /  attributed: /'
